// build-info.ts — Reads git/build metadata generated at dev/build time.
//
// The `src/build-info.generated.json` file is produced by the
// `generateBuildInfo` script invoked from vite.config.ts (see `buildInfoPlugin`).
// It may be missing before the first `vite dev`/`vite build` run, while tests
// run, or if generation failed — so we must load it defensively.
//
// Using `import.meta.glob` with `eager: true` keeps `getBuildInfo` synchronous
// and yields an empty object when the file is absent, which is exactly the
// "try import, fall back if missing" semantic the debug panel needs.

import type { BuildInfo } from '@my-copilot/shared'

const FALLBACK: BuildInfo = {
  git: null,
  buildTime: '',
  note: 'not built yet',
}

// Look up `../build-info.generated.json` (resolves to
// `apps/web/src/build-info.generated.json` from this file).
const modules = import.meta.glob('../build-info.generated.json', {
  eager: true,
  import: 'default',
}) as Record<string, unknown>

let cached: BuildInfo | null = null

/**
 * Returns the build info generated by the Vite `buildInfoPlugin`.
 *
 * Falls back to `{ git: null, buildTime: '', note: 'not built yet' }` when the
 * generated JSON is missing or malformed, so callers never have to handle an
 * absent file.
 */
export function getBuildInfo(): BuildInfo {
  if (cached) return cached

  for (const key of Object.keys(modules)) {
    const value = modules[key]
    if (value && typeof value === 'object') {
      cached = value as BuildInfo
      return cached
    }
  }

  cached = FALLBACK
  return cached
}
